# Generated by Django 6.1.1 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=2048)),
                (
                    "short_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, unique=True
                    ),
                ),
                (
                    "custom_alias",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
