# Generated by Django 6.1.1 on 2026-09-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("referrer", models.CharField(blank=True, max_length=2048)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("device", models.CharField(blank=True, max_length=20)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="urls.shorturl",
                    ),
                ),
            ],
        ),
    ]
